class MyCountry {
  final String name;
  final String isoCode; // ISO 3166-1 alpha-3 (e.g., UGA for Uganda)
  final String twoCode; // ISO 3166-1 alpha-2 (e.g., UG for Uganda)
  final String currency; // ISO 4217 currency code (e.g., UGX for Uganda)

  MyCountry({
    required this.name,
    required this.isoCode,
    required this.twoCode,
    required this.currency,
  });
}

final List<MyCountry> mycountries = [
  MyCountry(
      name: "Afghanistan", isoCode: "AFG", twoCode: "AF", currency: "AFN"),
  MyCountry(name: "Albania", isoCode: "ALB", twoCode: "AL", currency: "ALL"),
  MyCountry(name: "Algeria", isoCode: "DZA", twoCode: "DZ", currency: "DZD"),
  MyCountry(name: "Andorra", isoCode: "AND", twoCode: "AD", currency: "EUR"),
  MyCountry(name: "Angola", isoCode: "AGO", twoCode: "AO", currency: "AOA"),
  MyCountry(
      name: "Antigua and Barbuda",
      isoCode: "ATG",
      twoCode: "AG",
      currency: "XCD"),
  MyCountry(name: "Argentina", isoCode: "ARG", twoCode: "AR", currency: "ARS"),
  MyCountry(name: "Armenia", isoCode: "ARM", twoCode: "AM", currency: "AMD"),
  MyCountry(name: "Australia", isoCode: "AUS", twoCode: "AU", currency: "AUD"),
  MyCountry(name: "Austria", isoCode: "AUT", twoCode: "AT", currency: "EUR"),
  MyCountry(name: "Azerbaijan", isoCode: "AZE", twoCode: "AZ", currency: "AZN"),
  MyCountry(name: "Bahamas", isoCode: "BHS", twoCode: "BS", currency: "BSD"),
  MyCountry(name: "Bahrain", isoCode: "BHR", twoCode: "BH", currency: "BHD"),
  MyCountry(name: "Bangladesh", isoCode: "BGD", twoCode: "BD", currency: "BDT"),
  MyCountry(name: "Barbados", isoCode: "BRB", twoCode: "BB", currency: "BBD"),
  MyCountry(name: "Belarus", isoCode: "BLR", twoCode: "BY", currency: "BYN"),
  MyCountry(name: "Belgium", isoCode: "BEL", twoCode: "BE", currency: "EUR"),
  MyCountry(name: "Belize", isoCode: "BLZ", twoCode: "BZ", currency: "BZD"),
  MyCountry(name: "Benin", isoCode: "BEN", twoCode: "BJ", currency: "XOF"),
  MyCountry(name: "Bhutan", isoCode: "BTN", twoCode: "BT", currency: "BTN"),
  MyCountry(name: "Bolivia", isoCode: "BOL", twoCode: "BO", currency: "BOB"),
  MyCountry(
      name: "Bosnia and Herzegovina",
      isoCode: "BIH",
      twoCode: "BA",
      currency: "BAM"),
  MyCountry(name: "Botswana", isoCode: "BWA", twoCode: "BW", currency: "BWP"),
  MyCountry(name: "Brazil", isoCode: "BRA", twoCode: "BR", currency: "BRL"),
  MyCountry(name: "Brunei", isoCode: "BRN", twoCode: "BN", currency: "BND"),
  MyCountry(name: "Bulgaria", isoCode: "BGR", twoCode: "BG", currency: "BGN"),
  MyCountry(
      name: "Burkina Faso", isoCode: "BFA", twoCode: "BF", currency: "XOF"),
  MyCountry(name: "Burundi", isoCode: "BDI", twoCode: "BI", currency: "BIF"),
  MyCountry(name: "Cabo Verde", isoCode: "CPV", twoCode: "CV", currency: "CVE"),
  MyCountry(name: "Cambodia", isoCode: "KHM", twoCode: "KH", currency: "KHR"),
  MyCountry(name: "Cameroon", isoCode: "CMR", twoCode: "CM", currency: "XAF"),
  MyCountry(name: "Canada", isoCode: "CAN", twoCode: "CA", currency: "CAD"),
  MyCountry(
      name: "Central African Republic",
      isoCode: "CAF",
      twoCode: "CF",
      currency: "XAF"),
  MyCountry(name: "Chad", isoCode: "TCD", twoCode: "TD", currency: "XAF"),
  MyCountry(name: "Chile", isoCode: "CHL", twoCode: "CL", currency: "CLP"),
  MyCountry(name: "China", isoCode: "CHN", twoCode: "CN", currency: "CNY"),
  MyCountry(name: "Colombia", isoCode: "COL", twoCode: "CO", currency: "COP"),
  MyCountry(name: "Comoros", isoCode: "COM", twoCode: "KM", currency: "KMF"),
  MyCountry(name: "Congo", isoCode: "COG", twoCode: "CG", currency: "XAF"),
  MyCountry(name: "Costa Rica", isoCode: "CRI", twoCode: "CR", currency: "CRC"),
  MyCountry(name: "Croatia", isoCode: "HRV", twoCode: "HR", currency: "HRK"),
  MyCountry(name: "Cuba", isoCode: "CUB", twoCode: "CU", currency: "CUP"),
  MyCountry(name: "Cyprus", isoCode: "CYP", twoCode: "CY", currency: "EUR"),
  MyCountry(
      name: "Czech Republic", isoCode: "CZE", twoCode: "CZ", currency: "CZK"),
  MyCountry(name: "Denmark", isoCode: "DNK", twoCode: "DK", currency: "DKK"),
  MyCountry(name: "Djibouti", isoCode: "DJI", twoCode: "DJ", currency: "DJF"),
  MyCountry(name: "Dominica", isoCode: "DMA", twoCode: "DM", currency: "XCD"),
  MyCountry(
      name: "Dominican Republic",
      isoCode: "DOM",
      twoCode: "DO",
      currency: "DOP"),
  MyCountry(name: "Ecuador", isoCode: "ECU", twoCode: "EC", currency: "USD"),
  MyCountry(name: "Egypt", isoCode: "EGY", twoCode: "EG", currency: "EGP"),
  MyCountry(
      name: "El Salvador", isoCode: "SLV", twoCode: "SV", currency: "USD"),
  MyCountry(
      name: "Equatorial Guinea",
      isoCode: "GNQ",
      twoCode: "GQ",
      currency: "XAF"),
  MyCountry(name: "Eritrea", isoCode: "ERI", twoCode: "ER", currency: "ERN"),
  MyCountry(name: "Estonia", isoCode: "EST", twoCode: "EE", currency: "EUR"),
  MyCountry(name: "Eswatini", isoCode: "SWZ", twoCode: "SZ", currency: "SZL"),
  MyCountry(name: "Ethiopia", isoCode: "ETH", twoCode: "ET", currency: "ETB"),
  MyCountry(name: "Fiji", isoCode: "FJI", twoCode: "FJ", currency: "FJD"),
  MyCountry(name: "Finland", isoCode: "FIN", twoCode: "FI", currency: "EUR"),
  MyCountry(name: "France", isoCode: "FRA", twoCode: "FR", currency: "EUR"),
  MyCountry(name: "Gabon", isoCode: "GAB", twoCode: "GA", currency: "XAF"),
  MyCountry(name: "Gambia", isoCode: "GMB", twoCode: "GM", currency: "GMD"),
  MyCountry(name: "Georgia", isoCode: "GEO", twoCode: "GE", currency: "GEL"),
  MyCountry(name: "Germany", isoCode: "DEU", twoCode: "DE", currency: "EUR"),
  MyCountry(name: "Ghana", isoCode: "GHA", twoCode: "GH", currency: "GHS"),
  MyCountry(name: "Greece", isoCode: "GRC", twoCode: "GR", currency: "EUR"),
  MyCountry(name: "Grenada", isoCode: "GRD", twoCode: "GD", currency: "XCD"),
  MyCountry(name: "Guatemala", isoCode: "GTM", twoCode: "GT", currency: "GTQ"),
  MyCountry(name: "Guinea", isoCode: "GIN", twoCode: "GN", currency: "GNF"),
  MyCountry(
      name: "Guinea-Bissau", isoCode: "GNB", twoCode: "GW", currency: "XOF"),
  MyCountry(name: "Guyana", isoCode: "GUY", twoCode: "GY", currency: "GYD"),
  MyCountry(name: "Haiti", isoCode: "HTI", twoCode: "HT", currency: "HTG"),
  MyCountry(name: "Honduras", isoCode: "HND", twoCode: "HN", currency: "HNL"),
  MyCountry(name: "Hungary", isoCode: "HUN", twoCode: "HU", currency: "HUF"),
  MyCountry(name: "Iceland", isoCode: "ISL", twoCode: "IS", currency: "ISK"),
  MyCountry(name: "India", isoCode: "IND", twoCode: "IN", currency: "INR"),
  MyCountry(name: "Indonesia", isoCode: "IDN", twoCode: "ID", currency: "IDR"),
  MyCountry(name: "Iran", isoCode: "IRN", twoCode: "IR", currency: "IRR"),
  MyCountry(name: "Iraq", isoCode: "IRQ", twoCode: "IQ", currency: "IQD"),
  MyCountry(name: "Ireland", isoCode: "IRL", twoCode: "IE", currency: "EUR"),
  MyCountry(name: "Israel", isoCode: "ISR", twoCode: "IL", currency: "ILS"),
  MyCountry(name: "Italy", isoCode: "ITA", twoCode: "IT", currency: "EUR"),
  MyCountry(name: "Jamaica", isoCode: "JAM", twoCode: "JM", currency: "JMD"),
  MyCountry(name: "Japan", isoCode: "JPN", twoCode: "JP", currency: "JPY"),
  MyCountry(name: "Jordan", isoCode: "JOR", twoCode: "JO", currency: "JOD"),
  MyCountry(name: "Kazakhstan", isoCode: "KAZ", twoCode: "KZ", currency: "KZT"),
  MyCountry(name: "Kenya", isoCode: "KEN", twoCode: "KE", currency: "KES"),
  MyCountry(name: "Kiribati", isoCode: "KIR", twoCode: "KI", currency: "AUD"),
  MyCountry(
      name: "Korea, North", isoCode: "PRK", twoCode: "KP", currency: "KPW"),
  MyCountry(
      name: "Korea, South", isoCode: "KOR", twoCode: "KR", currency: "KRW"),
  MyCountry(name: "Kosovo", isoCode: "XKX", twoCode: "XK", currency: "EUR"),
  MyCountry(name: "Kuwait", isoCode: "KWT", twoCode: "KW", currency: "KWD"),
  MyCountry(name: "Kyrgyzstan", isoCode: "KGZ", twoCode: "KG", currency: "KGS"),
  MyCountry(name: "Laos", isoCode: "LAO", twoCode: "LA", currency: "LAK"),
  MyCountry(name: "Latvia", isoCode: "LVA", twoCode: "LV", currency: "EUR"),
  MyCountry(name: "Lebanon", isoCode: "LBN", twoCode: "LB", currency: "LBP"),
  MyCountry(name: "Lesotho", isoCode: "LSO", twoCode: "LS", currency: "LSL"),
  MyCountry(name: "Liberia", isoCode: "LBR", twoCode: "LR", currency: "LRD"),
  MyCountry(name: "Libya", isoCode: "LBY", twoCode: "LY", currency: "LYD"),
  MyCountry(
      name: "Liechtenstein", isoCode: "LIE", twoCode: "LI", currency: "CHF"),
  MyCountry(name: "Lithuania", isoCode: "LTU", twoCode: "LT", currency: "EUR"),
  MyCountry(name: "Luxembourg", isoCode: "LUX", twoCode: "LU", currency: "EUR"),
  MyCountry(name: "Madagascar", isoCode: "MDG", twoCode: "MG", currency: "MGA"),
  MyCountry(name: "Malawi", isoCode: "MWI", twoCode: "MW", currency: "MWK"),
  MyCountry(name: "Malaysia", isoCode: "MYS", twoCode: "MY", currency: "MYR"),
  MyCountry(name: "Maldives", isoCode: "MDV", twoCode: "MV", currency: "MVR"),
  MyCountry(name: "Mali", isoCode: "MLI", twoCode: "ML", currency: "XOF"),
  MyCountry(name: "Malta", isoCode: "MLT", twoCode: "MT", currency: "EUR"),
  MyCountry(
      name: "Marshall Islands", isoCode: "MHL", twoCode: "MH", currency: "USD"),
  MyCountry(name: "Mauritania", isoCode: "MRT", twoCode: "MR", currency: "MRU"),
  MyCountry(name: "Mauritius", isoCode: "MUS", twoCode: "MU", currency: "MUR"),
  MyCountry(name: "Mexico", isoCode: "MEX", twoCode: "MX", currency: "MXN"),
  MyCountry(name: "Micronesia", isoCode: "FSM", twoCode: "FM", currency: "USD"),
  MyCountry(name: "Moldova", isoCode: "MDA", twoCode: "MD", currency: "MDL"),
  MyCountry(name: "Monaco", isoCode: "MCO", twoCode: "MC", currency: "EUR"),
  MyCountry(name: "Mongolia", isoCode: "MNG", twoCode: "MN", currency: "MNT"),
  MyCountry(name: "Montenegro", isoCode: "MNE", twoCode: "ME", currency: "EUR"),
  MyCountry(name: "Morocco", isoCode: "MAR", twoCode: "MA", currency: "MAD"),
  MyCountry(name: "Mozambique", isoCode: "MOZ", twoCode: "MZ", currency: "MZN"),
  MyCountry(name: "Myanmar", isoCode: "MMR", twoCode: "MM", currency: "MMK"),
  MyCountry(name: "Namibia", isoCode: "NAM", twoCode: "NA", currency: "NAD"),
  MyCountry(name: "Nauru", isoCode: "NRU", twoCode: "NR", currency: "AUD"),
  MyCountry(name: "Nepal", isoCode: "NPL", twoCode: "NP", currency: "NPR"),
  MyCountry(
      name: "Netherlands", isoCode: "NLD", twoCode: "NL", currency: "EUR"),
  MyCountry(
      name: "New Zealand", isoCode: "NZL", twoCode: "NZ", currency: "NZD"),
  MyCountry(name: "Nicaragua", isoCode: "NIC", twoCode: "NI", currency: "NIO"),
  MyCountry(name: "Niger", isoCode: "NER", twoCode: "NE", currency: "XOF"),
  MyCountry(name: "Nigeria", isoCode: "NGA", twoCode: "NG", currency: "NGN"),
  MyCountry(
      name: "North Macedonia", isoCode: "MKD", twoCode: "MK", currency: "MKD"),
  MyCountry(name: "Norway", isoCode: "NOR", twoCode: "NO", currency: "NOK"),
  MyCountry(name: "Oman", isoCode: "OMN", twoCode: "OM", currency: "OMR"),
  MyCountry(name: "Pakistan", isoCode: "PAK", twoCode: "PK", currency: "PKR"),
  MyCountry(name: "Palau", isoCode: "PLW", twoCode: "PW", currency: "USD"),
  MyCountry(name: "Panama", isoCode: "PAN", twoCode: "PA", currency: "PAB"),
  MyCountry(
      name: "Papua New Guinea", isoCode: "PNG", twoCode: "PG", currency: "PGK"),
  MyCountry(name: "Paraguay", isoCode: "PRY", twoCode: "PY", currency: "PYG"),
  MyCountry(name: "Peru", isoCode: "PER", twoCode: "PE", currency: "PEN"),
  MyCountry(
      name: "Philippines", isoCode: "PHL", twoCode: "PH", currency: "PHP"),
  MyCountry(name: "Poland", isoCode: "POL", twoCode: "PL", currency: "PLN"),
  MyCountry(name: "Portugal", isoCode: "PRT", twoCode: "PT", currency: "EUR"),
  MyCountry(name: "Qatar", isoCode: "QAT", twoCode: "QA", currency: "QAR"),
  MyCountry(name: "Romania", isoCode: "ROU", twoCode: "RO", currency: "RON"),
  MyCountry(name: "Russia", isoCode: "RUS", twoCode: "RU", currency: "RUB"),
  MyCountry(name: "Rwanda", isoCode: "RWA", twoCode: "RW", currency: "RWF"),
  MyCountry(
      name: "Saint Kitts and Nevis",
      isoCode: "KNA",
      twoCode: "KN",
      currency: "XCD"),
  MyCountry(
      name: "Saint Lucia", isoCode: "LCA", twoCode: "LC", currency: "XCD"),
  MyCountry(
      name: "Saint Vincent and the Grenadines",
      isoCode: "VCT",
      twoCode: "VC",
      currency: "XCD"),
  MyCountry(name: "Samoa", isoCode: "WSM", twoCode: "WS", currency: "WST"),
  MyCountry(name: "San Marino", isoCode: "SMR", twoCode: "SM", currency: "EUR"),
  MyCountry(
      name: "Sao Tome and Principe",
      isoCode: "STP",
      twoCode: "ST",
      currency: "STN"),
  MyCountry(
      name: "Saudi Arabia", isoCode: "SAU", twoCode: "SA", currency: "SAR"),
  MyCountry(name: "Senegal", isoCode: "SEN", twoCode: "SN", currency: "XOF"),
  MyCountry(name: "Serbia", isoCode: "SRB", twoCode: "RS", currency: "RSD"),
  MyCountry(name: "Seychelles", isoCode: "SYC", twoCode: "SC", currency: "SCR"),
  MyCountry(
      name: "Sierra Leone", isoCode: "SLE", twoCode: "SL", currency: "SLL"),
  MyCountry(name: "Singapore", isoCode: "SGP", twoCode: "SG", currency: "SGD"),
  MyCountry(name: "Slovakia", isoCode: "SVK", twoCode: "SK", currency: "EUR"),
  MyCountry(name: "Slovenia", isoCode: "SVN", twoCode: "SI", currency: "EUR"),
  MyCountry(
      name: "Solomon Islands", isoCode: "SLB", twoCode: "SB", currency: "SBD"),
  MyCountry(name: "Somalia", isoCode: "SOM", twoCode: "SO", currency: "SOS"),
  MyCountry(
      name: "South Africa", isoCode: "ZAF", twoCode: "ZA", currency: "ZAR"),
  MyCountry(
      name: "South Sudan", isoCode: "SSD", twoCode: "SS", currency: "SSP"),
  MyCountry(name: "Spain", isoCode: "ESP", twoCode: "ES", currency: "EUR"),
  MyCountry(name: "Sri Lanka", isoCode: "LKA", twoCode: "LK", currency: "LKR"),
  MyCountry(name: "Sudan", isoCode: "SDN", twoCode: "SD", currency: "SDG"),
  MyCountry(name: "Suriname", isoCode: "SUR", twoCode: "SR", currency: "SRD"),
  MyCountry(name: "Sweden", isoCode: "SWE", twoCode: "SE", currency: "SEK"),
  MyCountry(
      name: "Switzerland", isoCode: "CHE", twoCode: "CH", currency: "CHF"),
  MyCountry(name: "Syria", isoCode: "SYR", twoCode: "SY", currency: "SYP"),
  MyCountry(name: "Taiwan", isoCode: "TWN", twoCode: "TW", currency: "TWD"),
  MyCountry(name: "Tajikistan", isoCode: "TJK", twoCode: "TJ", currency: "TJS"),
  MyCountry(name: "Tanzania", isoCode: "TZA", twoCode: "TZ", currency: "TZS"),
  MyCountry(name: "Thailand", isoCode: "THA", twoCode: "TH", currency: "THB"),
  MyCountry(
      name: "Timor-Leste", isoCode: "TLS", twoCode: "TL", currency: "USD"),
  MyCountry(name: "Togo", isoCode: "TGO", twoCode: "TG", currency: "XOF"),
  MyCountry(name: "Tonga", isoCode: "TON", twoCode: "TO", currency: "TOP"),
  MyCountry(
      name: "Trinidad and Tobago",
      isoCode: "TTO",
      twoCode: "TT",
      currency: "TTD"),
  MyCountry(name: "Tunisia", isoCode: "TUN", twoCode: "TN", currency: "TND"),
  MyCountry(name: "Turkey", isoCode: "TUR", twoCode: "TR", currency: "TRY"),
  MyCountry(
      name: "Turkmenistan", isoCode: "TKM", twoCode: "TM", currency: "TMT"),
  MyCountry(name: "Tuvalu", isoCode: "TUV", twoCode: "TV", currency: "AUD"),
  MyCountry(name: "Uganda", isoCode: "UGA", twoCode: "UG", currency: "UGX"),
  MyCountry(name: "Ukraine", isoCode: "UKR", twoCode: "UA", currency: "UAH"),
  MyCountry(
      name: "United Arab Emirates",
      isoCode: "ARE",
      twoCode: "AE",
      currency: "AED"),
  MyCountry(
      name: "United Kingdom", isoCode: "GBR", twoCode: "GB", currency: "GBP"),
  MyCountry(
      name: "United States", isoCode: "USA", twoCode: "US", currency: "USD"),
  MyCountry(name: "Uruguay", isoCode: "URY", twoCode: "UY", currency: "UYU"),
  MyCountry(name: "Uzbekistan", isoCode: "UZB", twoCode: "UZ", currency: "UZS"),
  MyCountry(name: "Vanuatu", isoCode: "VUT", twoCode: "VU", currency: "VUV"),
  MyCountry(
      name: "Vatican City", isoCode: "VAT", twoCode: "VA", currency: "EUR"),
  MyCountry(name: "Venezuela", isoCode: "VEN", twoCode: "VE", currency: "VES"),
  MyCountry(name: "Vietnam", isoCode: "VNM", twoCode: "VN", currency: "VND"),
  MyCountry(name: "Yemen", isoCode: "YEM", twoCode: "YE", currency: "YER"),
  MyCountry(name: "Zambia", isoCode: "ZMB", twoCode: "ZM", currency: "ZMW"),
  MyCountry(name: "Zimbabwe", isoCode: "ZWE", twoCode: "ZW", currency: "ZWL"),
];
