name: cyanase
description: "An investment app."
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.0.1
  country_picker: ^2.0.18
  sim_card_info: ^0.0.1
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.0
  web_socket_channel: ^2.4.0 # For WebSocket communication
  encrypt: ^5.0.0 # For encryption/decryption
  provider: ^6.0.5
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  audioplayers: ^6.1.0 # For playing audio
  record: ^4.4.0
  path_provider: ^2.1.5
  syncfusion_flutter_gauges: ^28.1.38
  awesome_notifications: ^0.10.0
  vibration: ^2.0.1
  contacts_service: ^0.6.3
  http: ^1.2.2
  crypto: ^3.0.2
  sqflite: ^2.2.1
  path: ^1.8.3
  libphonenumber: ^2.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  video_player: ^2.5.1
  share_plus: ^10.1.4
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.2
  animate_do: ^3.0.2
  qr_flutter: ^4.1.0
  lottie: ^3.1.2
  flutter_verification_code_field: ^1.0.0
  webdev: ^3.7.1
  web: ^1.1.1
  localstorage: ^5.0.0
  logging: ^1.3.0
  #smile_id: ^10.3.4
  http_parser: ^4.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Include assets like images and icons
  assets:
    - assets/images/logo.png
    - assets/images/deposit.png
    - assets/images/avatar.png
    - assets/images/vian.jpg
    - assets/icons/person.svg
    - assets/icons/groups.svg
    - assets/icons/goal-icon.svg
    - assets/images/back.svg
    - assets/images/white.png
    - assets/images/group.png
    - assets/images/done.png
    - assets/images/web.png
    - assets/images/goal.png
    - assets/animations/empty.json
    - assets/animations/group.json
  # Include custom fonts like Montserrat
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-VariableFont_wght.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
