name: cyanase
description: "An investment app."
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.0.1
  country_picker: ^2.0.18
  sim_card_info: ^0.0.1
  fl_chart: ^0.70.0
  flutter_svg: ^2.0.0
  flutter_lints: ^2.0.0
  web_socket_channel: ^2.4.0 # For WebSocket communication
  encrypt: ^5.0.0 # For encryption/decryption
  provider: ^6.0.5
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  audioplayers: ^6.1.0  # For playing audio
  record: ^4.4.0    
  path_provider: ^2.1.5    # For recording audio

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Include assets like images and icons
  assets:
    - assets/images/logo.png
    - assets/images/vian.jpg
    - assets/icons/person.svg
    - assets/icons/groups.svg
    - assets/icons/goal-icon.svg
    - assets/images/back.svg

  # Include custom fonts like Montserrat
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic