name: cyanase
description: An investment app.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI and UX
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  provider: ^6.0.5
  animate_do: ^3.0.2
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
 

  # Phone, SIM, and Contacts
  intl_phone_field: ^3.0.1
  flutter_libphonenumber: ^2.5.1
  country_picker: ^2.0.18
  sim_card_info: ^0.0.1
  flutter_contacts: ^1.1.9+2

  # Notifications and Device Features
  awesome_notifications: ^0.10.1
  vibration: ^2.0.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.2

  # Media and File Handling
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  video_player: ^2.5.1
  file_picker: ^10.1.9
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  cached_network_image: ^3.2.3

  # Charts and Gauges
  fl_chart: ^0.65.0
  syncfusion_flutter_gauges: ^24.1.41
  syncfusion_flutter_core: ^24.1.41

  # Data and State
  http: ^1.2.2
  sqflite: ^2.2.1
  path: ^1.8.3
  path_provider: ^2.1.5
  localstorage: ^5.0.0
  rxdart: ^0.28.0
  logging: ^1.3.0
  crypto: ^3.0.2
  encrypt: ^5.0.0
  http_parser: ^4.0.2
  flutter_blurhash: ^0.9.1

  # Real-time and Deep Linking
  web_socket_channel: ^2.4.0
  app_links: ^6.4.0
  url_launcher: ^6.3.1

  # Voice and Audio
  audioplayers: ^6.1.0
  record: ^4.4.0

  # QR and Emoji
  qr_flutter: ^4.1.0
  emoji_picker_flutter: ^4.3.0

  # OTP
  pin_code_fields: ^8.0.1

  # Web support
  web: ^1.1.1
  flutter_local_notifications: ^19.2.1
  socket_io_client: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/deposit.png
    - assets/images/avatar.png
    - assets/images/vian.jpg
    - assets/images/white.png
    - assets/images/group.png
    - assets/images/done.png
    - assets/images/web.png
    - assets/images/goal.png
    - assets/icons/person.svg
    - assets/icons/groups.svg
    - assets/icons/goal-icon.svg
    - assets/images/back.svg
    - assets/animations/empty.json
    - assets/animations/group.json

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-VariableFont_wght.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

dependency_overrides:
  intl: ^0.18.0
